### ISSUE TITLE
Unable to execute swap participants

### ISSUE THREAD

**Issue by tacettinaksu** [salesforce/scv-connector-base#35]
Hi,

While trying to swap participants in voice call by using demo-svc-connector [downloaded @16 Jan 2023] , we are getting the following error. We are using latest versions of libraries also.

Any help will be appreciated. 

```
SCV dispatched error CAN_NOT_SWAP_PARTICIPANTS for eventType SWAP_PARTICIPANTS Error: Invalid className. Expecting object of class function t(e) {
        var E = e.callId,
          n = e.callType,
          a = e.contact,
          r = e.state,
          T = e.callAttributes,
          _ = e.phoneNumber,
          o = e.callInfo,
          i = e.reason,
          s = e.closeCallOnError,
          A = e.agentStatus;
        p()(this, t), E && (rt.validateString(E), this.callId = E), n && (rt.validateEnum(n, Object.values(N.CALL_TYPE)), this.callType = n), _ && (rt.validateString(_), this.phoneNumber = _), o && (rt.validateClassObject(o, tt), this.callInfo = o), a && (rt.validateClassObject(a, et), this.contact = a), i && (this.reason = i), s && (this.closeCallOnError = s), A && (this.agentStatus = A), this.state = r, this.callAttributes = T;
      } but got object
    at Function.value (types.js:1039:19)
    at types.js:367:27
    at Array.forEach (<anonymous>)
    at new t (types.js:366:34)
    at Sdk.swapCalls (vendor-sdk.js:927:47)
    at Connector.swap (connector.js:113:25)
    at baseConnector.js:372:55
    at i (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
```

**Comment by estrudels** [comment]
@tacettinaksu Are you still facing this issue? Or you are now resolved?

**Comment by tacettinaksu** [comment]
@estrudels it has been so long, we solved this with a workaround and I switched another topic already in another company. Feel free to close if it does not make sense to investigate. Best.

**Comment by estrudels** [comment]
@tacettinaksu Thanks for the consent, however I don't have the ability to close!

If you could perform the action yourself that be great! 🙂

Thanks!
